"""Author the hand-built synthetic Capytaine NetCDF fixtures used in
``tests/unit/test_capytaine_reader.py``.

Capytaine itself is not a runtime dependency of FloatSim (CLAUDE.md §9),
so the synthetic fixtures cannot be generated by running Capytaine on
the fly inside the test process. Instead, this script writes NetCDF
files that mirror Capytaine's documented schema (see
``capytaine.io.xarray.assemble_dataset`` /
``separate_complex_values``):

  dims:
    omega                (rad/s, float64; may contain +inf for A_inf)
    wave_direction       (rad, float64)
    radiating_dof        (string DOF name)
    influenced_dof       (string DOF name)
    complex              (size 2, ['re', 'im'])

  data_vars:
    added_mass(omega, radiating_dof, influenced_dof)            float64
    radiation_damping(omega, radiating_dof, influenced_dof)     float64
    excitation_force(complex, omega, wave_direction, influenced_dof)
                                                                float64
    hydrostatic_stiffness(radiating_dof, influenced_dof)        float64

The split-complex layout (``complex`` dim of size 2) matches Capytaine's
``separate_complex_values`` workaround for NetCDF's lack of native
complex support.

Two fixtures are produced:

  ``synthetic_simple.nc``
      Two finite frequencies + one ``omega = +inf`` sample, two wave
      directions. Diagonal radiation only; non-trivial excitation phase
      so the reader's lags->leads conjugation is observable.

  ``synthetic_sphere.nc``
      Fully submerged sphere at depth >= 5R (Q4 of M5). Analytical
      ``A_ii = (2/3) * pi * rho * R**3`` for surge / sway / heave (and
      zero off-diagonal), B_ii = 0, C = 0, F_exc = 0 (deeply submerged
      neutral-buoyancy body has no first-order wave excitation at
      wave frequencies of interest, to leading order). The sphere
      fixture is what M5 PR3 cross-checks against the analytical
      reference and the WAMIT/OrcaFlex sphere outputs.

The output ``.nc`` files are committed under
``tests/fixtures/bem/capytaine/``. Re-running the script overwrites
them deterministically.

Usage::

    python scripts/build_capytaine_synthetic_fixtures.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import xarray as xr

# DOF names match Capytaine's defaults for the standard 6-DOF rigid-body
# decomposition. Capytaine itself accepts arbitrary DOF labels; the
# reader requires these exact six names.
_CAPYTAINE_DOF_NAMES: tuple[str, ...] = (
    "Surge",
    "Sway",
    "Heave",
    "Roll",
    "Pitch",
    "Yaw",
)


def _split_complex(arr: np.ndarray) -> np.ndarray:
    """Mirror ``capytaine.io.xarray.separate_complex_values`` for one variable.

    Stack real and imaginary parts along a new leading axis of size 2.
    """
    return np.stack([np.real(arr), np.imag(arr)], axis=0)


def _build_synthetic_simple(rho: float = 1025.0) -> xr.Dataset:
    """Two finite omegas + one +inf omega; two wave directions; diagonal radiation."""
    # Finite + infinite frequency samples. The +inf row is Capytaine's
    # native way of carrying A_inf in the same dataset.
    omega = np.array([0.5, 1.0, np.inf], dtype=np.float64)
    wave_direction_rad = np.deg2rad(np.array([0.0, 45.0], dtype=np.float64))

    # Diagonal added mass: distinct values per DOF; B = 0 for omega = inf.
    n_w = omega.size
    n_dof = len(_CAPYTAINE_DOF_NAMES)
    A = np.zeros((n_w, n_dof, n_dof), dtype=np.float64)
    B = np.zeros_like(A)
    diag_at_finite = np.array([1.0e5, 1.1e5, 1.2e5, 1.0e7, 1.1e7, 1.2e7])
    diag_at_inf = diag_at_finite * 0.5  # high-frequency limit < finite-omega values
    for k, w in enumerate(omega):
        if np.isinf(w):
            np.fill_diagonal(A[k], diag_at_inf)
            # B(inf) is physically zero.
        else:
            np.fill_diagonal(A[k], diag_at_finite * (1.0 + 0.1 * k))
            np.fill_diagonal(
                B[k], 5.0e3 * (1.0 + 0.05 * k) * np.array([1.0, 1.1, 1.2, 1.0e2, 1.1e2, 1.2e2])
            )

    # Excitation force (lags convention, Capytaine-native): pick a known
    # phase so the reader's conjugation flips it to a known leads-phase.
    # Magnitude: 1e6 N at heading 0, 5e5 N at heading 45 deg.
    n_h = wave_direction_rad.size
    F_exc = np.zeros((n_w, n_h, n_dof), dtype=np.complex128)
    # Only define excitation at the finite-omega rows; Capytaine emits NaN
    # at omega=inf for excitation, but to keep the fixture small we just
    # write zero there. The reader strips the inf row from finite-omega
    # data anyway.
    for k, w in enumerate(omega):
        if np.isinf(w):
            continue
        for h, _beta_rad in enumerate(wave_direction_rad):
            mag = 1.0e6 * (1.0 - 0.1 * k) * (1.0 if h == 0 else 0.5)
            phase_lags_rad = np.deg2rad(30.0 + 10.0 * k + 5.0 * h)
            # heave gets the magnitude; other DOFs get zero excitation
            # to keep the fixture trivially inspectable.
            F_exc[k, h, 2] = mag * np.exp(-1j * phase_lags_rad)
            # Surge gets a complex, frequency-dependent phase
            F_exc[k, h, 0] = (mag * 0.3) * np.exp(-1j * (phase_lags_rad + np.deg2rad(20.0)))

    # Hydrostatic stiffness: only heave / roll / pitch entries.
    C = np.zeros((n_dof, n_dof), dtype=np.float64)
    C[2, 2] = 4.0e5  # heave
    C[3, 3] = 7.0e6  # roll
    C[4, 4] = 7.0e6  # pitch

    return _build_dataset(
        omega=omega,
        wave_direction_rad=wave_direction_rad,
        added_mass=A,
        radiation_damping=B,
        excitation_force=F_exc,
        hydrostatic_stiffness=C,
        rho=rho,
        body_name="synthetic_simple",
    )


def _build_synthetic_sphere(rho: float = 1025.0, R: float = 1.0) -> xr.Dataset:
    """Fully submerged sphere at depth >= 5R; analytical reference (Q4)."""
    # Frequency-independent because the sphere is deeply submerged
    # (Lamb 1932, Sec. 92). Use a short omega grid plus omega=inf so the
    # reader handles the same shape as the finite-frequency case.
    omega = np.array([0.3, 0.7, 1.4, np.inf], dtype=np.float64)
    wave_direction_rad = np.deg2rad(np.array([0.0, 90.0], dtype=np.float64))

    A_ii = (2.0 / 3.0) * np.pi * rho * R**3  # ~ 2147 kg for R=1 m, rho=1025
    n_w = omega.size
    n_dof = len(_CAPYTAINE_DOF_NAMES)

    A = np.zeros((n_w, n_dof, n_dof), dtype=np.float64)
    for k in range(n_w):
        # Translational DOFs: A_ii. Rotational DOFs: zero (point sphere
        # has no rotational added mass).
        A[k, 0, 0] = A_ii
        A[k, 1, 1] = A_ii
        A[k, 2, 2] = A_ii

    # Radiation damping: zero for a deeply submerged body (no
    # free-surface radiation reaches the sphere).
    B = np.zeros_like(A)

    # Excitation: zero at this depth to leading order (decays as e^{kz}
    # for z << 0). Real Capytaine would report tiny nonzero values from
    # numerical diffraction noise; the synthetic case sets exactly zero.
    F_exc = np.zeros((n_w, wave_direction_rad.size, n_dof), dtype=np.complex128)

    # Neutral buoyancy + fully submerged -> hydrostatic stiffness is
    # zero (no waterplane).
    C = np.zeros((n_dof, n_dof), dtype=np.float64)

    return _build_dataset(
        omega=omega,
        wave_direction_rad=wave_direction_rad,
        added_mass=A,
        radiation_damping=B,
        excitation_force=F_exc,
        hydrostatic_stiffness=C,
        rho=rho,
        body_name="synthetic_sphere",
        extra_attrs={
            "sphere_radius_m": float(R),
            "sphere_submergence_depth_m": float(5.0 * R),
            "analytical_added_mass_kg": float(A_ii),
        },
    )


def _build_dataset(
    *,
    omega: np.ndarray,
    wave_direction_rad: np.ndarray,
    added_mass: np.ndarray,
    radiation_damping: np.ndarray,
    excitation_force: np.ndarray,
    hydrostatic_stiffness: np.ndarray,
    rho: float,
    body_name: str,
    extra_attrs: dict[str, float] | None = None,
) -> xr.Dataset:
    """Assemble the xarray Dataset in Capytaine's on-disk schema.

    Complex variables are stored split into real/imag parts along a
    leading ``complex`` dim of size 2 with coordinate values
    ``['re', 'im']`` -- matching Capytaine's
    ``separate_complex_values``.
    """
    dofs = list(_CAPYTAINE_DOF_NAMES)

    F_split = _split_complex(excitation_force)  # (2, n_w, n_h, n_dof)

    ds = xr.Dataset(
        data_vars={
            "added_mass": (
                ("omega", "radiating_dof", "influenced_dof"),
                added_mass,
                {"long_name": "Added mass"},
            ),
            "radiation_damping": (
                ("omega", "radiating_dof", "influenced_dof"),
                radiation_damping,
                {"long_name": "Radiation damping"},
            ),
            "excitation_force": (
                ("complex", "omega", "wave_direction", "influenced_dof"),
                F_split,
                {"long_name": "Excitation force"},
            ),
            "hydrostatic_stiffness": (
                ("radiating_dof", "influenced_dof"),
                hydrostatic_stiffness,
                {"long_name": "Hydrostatic stiffness"},
            ),
        },
        coords={
            "omega": (
                ("omega",),
                omega,
                {"long_name": "Angular frequency", "units": "rad/s"},
            ),
            "wave_direction": (
                ("wave_direction",),
                wave_direction_rad,
                {"long_name": "Wave direction", "units": "rad"},
            ),
            "radiating_dof": (("radiating_dof",), np.array(dofs, dtype="U16")),
            "influenced_dof": (("influenced_dof",), np.array(dofs, dtype="U16")),
            "complex": (("complex",), np.array(["re", "im"], dtype="U2")),
        },
        attrs={
            "creation_of_dataset": "synthetic-fixture (FloatSim test suite)",
            "rho": float(rho),
            "g": 9.80665,
            "body_name": body_name,
            "water_depth": float("inf"),
            "capytaine_version": "synthetic",
            **(extra_attrs or {}),
        },
    )
    return ds


def _save(ds: xr.Dataset, path: Path) -> None:
    """Write to NetCDF using NetCDF4 string encoding (Capytaine's workaround)."""
    encoding = {
        "radiating_dof": {"dtype": "S16"},
        "influenced_dof": {"dtype": "S16"},
        "complex": {"dtype": "S2"},
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    ds.to_netcdf(path, encoding=encoding)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dst",
        type=Path,
        default=Path("tests/fixtures/bem/capytaine"),
        help="Destination directory for the synthetic .nc fixtures.",
    )
    args = parser.parse_args(argv)
    dst: Path = args.dst

    simple = _build_synthetic_simple()
    sphere = _build_synthetic_sphere()

    out_simple = dst / "synthetic_simple.nc"
    out_sphere = dst / "synthetic_sphere.nc"
    _save(simple, out_simple)
    _save(sphere, out_sphere)

    print(f"  wrote {out_simple} ({out_simple.stat().st_size} bytes)")
    print(f"  wrote {out_sphere} ({out_sphere.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
